#!/usr/bin/env python3

# This file is part of cmk-Tado.
# cmk-Tado is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation in version 2.
# cmk-Tado is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with cmk-Tado.
# If not, see <https://www.gnu.org/licenses/>.


from cmk.base.check_api import passwordstore_get_cmdline
from cmk.base.config import special_agent_info


# Get params passed via WATO
def agent_tado_arguments(params, username, password):
    args = []
    args += ["-u", params["username"]]
    args += ["-p", passwordstore_get_cmdline("%s", params["password"])]
    if (filters := params.get("filters")) is not None:
        if (home := filters.get("home")) is not None:
            args += ["-o", home]
        if (zone := filters.get("zone")) is not None:
            args += ["-z", zone]
    return args


# Register special agent
special_agent_info["tado"] = agent_tado_arguments
